name: Temporary Action For Rentify

on: [push]

jobs:
  tugas-pertama-saya:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Mencetak pesan sapaan
        run: echo "Hello."
        
      - name: Menampilkan tanggal dan waktu server
        run: date